export const NEWS_BODY_REQUEST = 'NEWS_BODY_REQUEST';
export const NEWS_BODY_REQUEST_SUCCESS = 'NEWS_BODY_REQUEST_SUCCESS';
export const NEWS_BODY_REQUEST_FAILURE = 'NEWS_BODY_REQUEST_FAILURE';
export const SHOW_NEWS_BODY = 'SHOW_NEWS_BODY';
